// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOIms9eoZYMvw9aEBpGTpFa5YXHb7qgE',
    appId: '1:744889553727:web:fed655a51f25a2ca84f98a',
    messagingSenderId: '744889553727',
    projectId: 'application-973de',
    authDomain: 'application-973de.firebaseapp.com',
    storageBucket: 'application-973de.appspot.com',
    measurementId: 'G-V3CD7D8R4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwrZGetX6W1R25-1RDd8ZIIj0w0PPs6M',
    appId: '1:744889553727:android:0514a2ec007c4cbe84f98a',
    messagingSenderId: '744889553727',
    projectId: 'application-973de',
    storageBucket: 'application-973de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRhhsyq6AXN4xYUc-9euUV8GUnbjuAltg',
    appId: '1:744889553727:ios:b0ceb3b5b6dfa9a584f98a',
    messagingSenderId: '744889553727',
    projectId: 'application-973de',
    storageBucket: 'application-973de.appspot.com',
    androidClientId: '744889553727-9nhmqj23qv5i9scrkk883vfnerdat607.apps.googleusercontent.com',
    iosClientId: '744889553727-74guhl492vdpue278k2k5a31hh5t8ktq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRhhsyq6AXN4xYUc-9euUV8GUnbjuAltg',
    appId: '1:744889553727:ios:f40ed2ffe892b21e84f98a',
    messagingSenderId: '744889553727',
    projectId: 'application-973de',
    storageBucket: 'application-973de.appspot.com',
    androidClientId: '744889553727-9nhmqj23qv5i9scrkk883vfnerdat607.apps.googleusercontent.com',
    iosClientId: '744889553727-7mprk65kk2f5e9rul9b35ppa4kcrqgdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapplication.RunnerTests',
  );
}
